### ISSUE TITLE
[REQUEST] - VLC, Brave, Gradience and Chromium

### ISSUE THREAD

**Issue by SubatomicCat** [Frostbitten-jello/Skeuowaita#4] opened 2023-01-14 13:44 UTC
Hey, I am really enjoying this icon theme. Thanks for making it.
I would like to request a few icons:

VLC: org.videolan.VLC
Brave: com.brave.Browser
Gradience: com.github.GradienceTeam.Gradience
Chromium: org.chromium.Chromium / com.github.Eloston.UngoogledChromium

Hope it is not too many.

**Comment by Frostbitten-jello** [comment] 2023-01-16 03:53
I have created a new issue which will have all the pending icon requests so people making new requests can look up if the request is already been made. Just to prevent duplicate requests. So will close this issue as a duplicate.

**Comment by Frostbitten-jello** [comment] 2023-01-16 03:54
Duplicate of #7

**Comment by Frostbitten-jello** [comment] 2023-01-21 06:26
@SubatomicCat added an icon for VLC, check it out and lemme know what you think! (its not final but yea)

**Comment by stpnwf** [comment] 2023-01-21 23:52
> @SubatomicCat added an icon for VLC, check it out and lemme know what you think! (its not final but yea)

Hey, I like how it is coming along! But personally I prefer the square base. It makes it look more like a traffic cone and less like a hat imo.

**Comment by SubatomicCat** [comment] 2023-01-22 13:05
> @SubatomicCat added an icon for VLC, check it out and lemme know what you think! (its not final but yea)

Hey, I like how it is coming along! But personally I prefer the square base. It makes it look more like a traffic cone and less like a hat imo.

**Comment by Frostbitten-jello** [comment] 2023-01-23 07:59
@SubatomicCat thanks for the feedback, I did the square bottom

**Comment by SubatomicCat** [comment] 2023-01-24 16:24
I like it a lot more! Thanks. Also rly like the Chromium icon!

**Comment by Frostbitten-jello** [comment] 2023-04-22 16:38
@SubatomicCat after so much procrastination I finally made the gradience icon, whewww!! let me know what you think :)

**Closed by Frostbitten-jello** 2023-04-22 16:38 UTC
Labels: Icon request, Work in progress

**Comment by stpnwf** [comment] 2023-04-28 21:36
I love it! Thank you, no worries. Def take your time.
