### ISSUE TITLE
[Request] Kitty 

### ISSUE THREAD

**Issue by CaitlinDavitt** [Frostbitten-jello/Skeuowaita#6] opened 2023-01-15 16:02 UTC
I would like to request an icon for the Kitty terminal emulator. 

GitHub: https://github.com/kovidgoyal/kitty
Website: https://sw.kovidgoyal.net/kitty/

Paths: 
```
/usr/share/icons/hicolor/scalable/apps/kitty.svg
/usr/share/icons/hicolor/256x256/apps/kitty.png
```

I am excited to see what you can do with this :)

**Comment by Frostbitten-jello** [comment] 2023-01-16 03:55
I have created a new issue which will have all the pending icon requests so people making new requests can look up if the request is already been made. Just to prevent duplicate requests. So will close this issue as a duplicate.

**Comment by Frostbitten-jello** [comment] 2023-01-16 03:55
Duplicate of #7

**Comment by Frostbitten-jello** [comment] 2023-04-04 18:36
@CaitlinDavitt 

After so many failed attempts I finally made something that I felt good about, let me know what you think !!

![bitmap](https://user-images.githubusercontent.com/120028833/229886872-6396076d-ff89-4137-9f85-823cb222d9c8.png)

**Closed** 2023-04-08 03:58 UTC
Labels: Icon request, Work in progress
