### ISSUE TITLE
Development software icons (Jetbrains IDEs and Godot)

### ISSUE THREAD

**Issue by PauloVBettio** [Frostbitten-jello/Skeuowaita#13] opened 2023-04-10 01:36 UTC
Your icon pack is awesome! You are doing an amazing work!

I have some suggestions of icons related to software development.

Jetbrains:

- [x] com.jetbrains.toolbox
- [x] com.jetbrains.CLion
- [x] com.jetbrains.DataGrip
- [x] com.jetbrains.dataspell
- [x] com.jetbrains.GoLand
- [x] com.jetbrains.IntelliJ-IDEA-Community
- [x] com.jetbrains.IntelliJ-IDEA-Ultimate
- [x] com.jetbrains.PhpStorm
- [x] com.jetbrains.PyCharm-Community
- [x] com.jetbrains.PyCharm-Professional
- [x] com.jetbrains.Rider
- [x] com.jetbrains.RubyMine
- [x] com.jetbrains.WebStorm

Godot:

- [x] org.godotengine.Godot

Others:

- [x] [org.gaphor.Gaphor](https://gaphor.org/)
- [x] [rest.insomnia.Insomnia](https://insomnia.rest)

**Comment by Frostbitten-jello** [comment] 2023-04-10 05:09
Duplicate of #7

**Comment by Frostbitten-jello** [comment] 2023-04-26 15:38
@PauloVBettio just added icons for all jetbrains apps, let me know what you think

**Comment by PauloVBettio** [comment] 2023-04-26 16:08
> @PauloVBettio just added icons for all jetbrains apps, let me know what you think

They are great, nice work!

**Comment by CodexDevv** [comment] 2023-04-26 19:25
@Frostbitten-jello 
Please add sublime-text.svg (right now is only sublime_text.svg)
Also vscode.svg (right now is com.visualstudio.code.org)

**Comment by Frostbitten-jello** [comment] 2023-04-27 02:10
@CodexDevv just added !!

**Comment by Frostbitten-jello** [comment] 2023-05-22 09:19
@PauloVBettio finished all of them !! let me know what you think :)

**Closed** 2023-05-22 09:19 UTC
Labels: Icon request, Work in progress
