### ISSUE TITLE
[Request] Transmission

### ISSUE THREAD

**Issue by funkycode** [Frostbitten-jello/Skeuowaita#5] opened 2023-01-14 15:01 UTC
Transmission is opensource bittorrent client
Icons for GTK on offcial repo: https://github.com/transmission/transmission/tree/main/gtk/icons
Icons I found on system:
```
/usr/share/icons/HighContrast/16x16/apps/transmission.png
/usr/share/icons/HighContrast/22x22/apps/transmission.png
/usr/share/icons/HighContrast/24x24/apps/transmission.png
/usr/share/icons/HighContrast/256x256/apps/transmission.png
/usr/share/icons/HighContrast/32x32/apps/transmission.png
/usr/share/icons/HighContrast/48x48/apps/transmission.png
```

**Comment by Frostbitten-jello** [comment] 2023-01-16 03:55
I have created a new issue which will have all the pending icon requests so people making new requests can look up if the request is already been made. Just to prevent duplicate requests. So will close this issue as a duplicate.

**Comment by Frostbitten-jello** [comment] 2023-01-16 03:55
Duplicate of #7

**Closed by Frostbitten-jello** 2023-01-16 03:55 UTC

**Comment by Frostbitten-jello** [comment] 2023-01-16 13:51
@funkycode I have added the icon for transmission :)
