### ISSUE TITLE
Some icons don't get applied? + [Request] VSCode, Sublime Text

### ISSUE THREAD

**Issue by CodexDevv** [Frostbitten-jello/Skeuowaita#12] opened 2023-04-07 12:47 UTC
Hello.

So it might be a ME-problem, as for example, the chrome icon didn't get applied (chrome install via .rpm package from official website).

Screenshot of problem:
[https://i.imgur.com/05BENAV.png](url)

Also, with this occasion, I would love to make a request for the following applications (I'm not sure i have the right domains):

- VS Code: com.visualstudio.code / code
- Sublime Text: sublime_text

**Comment by CodexDevv** [comment] 2023-04-07 12:52
Apparently, the .rpm installed files, have different .desktop files, so what I had to do was go into where the icons are located, and just copy the chrome icon and rename it to what the .desktop one.

`sudo cp com.google.Chrome.svg google-chrome.svg`

**Comment by Frostbitten-jello** [comment] 2023-04-08 04:20
> Apparently, the .rpm installed files, have different .desktop files, so what I had to do was go into where the icons are located, and just copy the chrome icon and rename it to what the .desktop one.
> 
> `sudo cp com.google.Chrome.svg google-chrome.svg`

Yess that is an issue with different distributing formats, they use different naming schemes, that is why I added a [Section](https://github.com/Frostbitten-jello/Skeuowaita#requesting-new-icons) to Readme.

so the icon that was missing was `google-chrome.svg` for google chrome right? I will add that icon to the icon pack so it won't be an issue in future (just confirm it so I will be sure)

**Comment by Frostbitten-jello** [comment] 2023-04-08 04:21
> * VS Code: com.visualstudio.code / code
> 
> * Sublime Text: sublime_text

Duplicate of #7

**Comment by CodexDevv** [comment] 2023-04-08 11:04
> so the icon that was missing was `google-chrome.svg` for google chrome right? I will add that icon to the icon pack so it won't be an issue in future (just confirm it so I will be sure)

Yes. That was it.

**Comment by Frostbitten-jello** [comment] 2023-04-08 13:34
@CodexDevv I have added the icon, you won't need to rename it now. You can clone it again if you like.

**Closed by Frostbitten-jello** 2023-04-08 13:34 UTC
Labels: bug, Icon request, Work in progress
